//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormulaInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engine
    {
        public int EngineID { get; set; }
        public decimal Litres { get; set; }
        public int Revolutions { get; set; }
        public int Pistons { get; set; }
        public decimal Price { get; set; }
    }
}
