//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormulaInventory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Wheel
    {
        [Required]
        public int WheelID { get; set; }
        [Required]
        public decimal RimSize { get; set; }
        [Required]
        public string Color { get; set; }
        [Required]
        public string Material { get; set; }
        [Required]
        public decimal Price { get; set; }
    }
}
